name: to_do_list
description: A basic to-do list application, done as a task for a job interview.
# version: 1.0.0
#author: hasanalimam <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  bootjack: ^1.0.0+1

dev_dependencies:
  build_runner: ^0.10.0
  build_web_compilers: ^0.4.0
